{
    "openapi" : "3.0.0",
    "info": {
        "title" : "API Renpass.Uol",
        "description" : "Está é uma API RestFull com objetivo de cadastro de usuários, veículos e locadoras de veículos",
        "termsOfService" : "",
        "contact" : {
            "email" : "fernando@email.com"
        },
        "version" : "1.0.0"        
    },
    "servers" : [
        {
            "url" : "http://localhost:3000/api/v1/",
            "description": "API Runpass.Uol"
        }
    ],
    "paths" : {
        "/person" : {
            "post" : {
                "summary" : "Cadastro de usuário",
                "description" : "Essa rota será responsável por cadastrar um novo usuário",
                "tags" : ["Person"],
                "security" : [{"bearerAuth" : []}],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/person"                                 
                            },
                            "examples" : {
                                "person" : {
                                    "value" : {
                                        "name" : "Fernando Torres",
                                        "cpf" : "000.000.000-00",
                                        "birthDay" : "29/06/1987",
                                        "email" : "fernando@email.com",
                                        "password" : "123456",
                                        "canDrive" : "yes"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "400": {
                        "description" : "Bad Request"
                    },
                    "201" : {
                        "description" : "User registered successfully",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/person"                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/person/" : {
            "get" : {
                "description" : "Busca todos os usuários cadastrados",
                "summary" : "Busca todos os usuários cadastrados",
                "tags" : ["Person"],
                "responses" : {
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/person"                                    
                                }
                            }
                        }
                    }
                }
            }

        },
        "/person/{listId}" : {
            "get" : {
                "description" : "Busca um usuário cadastrado pelo ID",
                "summary" : "Busca um usuário cadastrado pelo ID",
                "tags" : ["Person"],
                "parameters" :  [
                    {
                        "name" : "listId",
                        "in" : "path",
                        "description" : "Id de usuário cadastrado para busca",
                        "required" : true
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "Usuário encontrado com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/person"                                    
                                }
                            }
                        }
                    }
                }
            }            
        },
        "/person/{update}" : {
            "put" : {                
                "description" : "Atualiza os dados de um usuário cadastrado pelo ID",
                "summary" : "Atualiza os dados de um usuário cadastrado pelo ID",
                "tags" : ["Person"],
                "security" : [{ "bearerAuth" : [] }],
                "parameters" :  [
                    {
                        "name" : "update",
                        "in" : "path",
                        "description" : "Id de usuário cadastrado para busca",
                        "required" : true
                    }
                ],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/person"                                 
                            },
                            "examples" : {
                                "person" : {
                                    "value" : {
                                        "name" : "Fernando Torres",
                                        "cpf" : "000.000.000-00",
                                        "birthDay" : "29/06/1987",
                                        "email" : "fernando@email.com",
                                        "password" : "123456",
                                        "canDrive" : "yes"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "200" : {
                        "description" : "Dados de usuário atualizados com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/person"                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/person/{delete}" : {
            "delete" : {
                "description" : "Exclui os dados de um usuário cadastrado pelo ID",
                "summary" : "Exclui os dados de um usuário cadastrado pelo ID",
                "tags" : ["Person"],
                "parameters" :  [
                    {
                        "name" : "delete",
                        "in" : "path",
                        "description" : "Id de usuário cadastrado para busca e exclusão dos dados",
                        "required" : true
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "Dados de usuário excluidos com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/person"                                    
                                }
                            }
                        }
                    }
                }
            }            
        },
        "/car" : {
            "post" : {
                "summary" : "Cadastro de veículo",
                "description" : "Essa rota será responsável por cadastrar um novo veículo",
                "tags" : ["Car"],
                "security" : [{"bearerAuth" : []}],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/car"                                 
                            },
                            "examples" : {
                                "car" : {
                                    "value" : {
                                        "model" : "S10 2.8",
                                        "type" : "Sedan",
                                        "brand" : "GM",
                                        "color" : "branco",
                                        "year" : "2021",                                        
                                        "accessories": [
                                            {
                                              "description": "Ar-condicionado"                                              
                                            },
                                            {
                                              "description": "Dir. Hidráulica"                                              
                                            },
                                            {
                                              "description": "Cabine Dupla"                                              
                                            },
                                            {
                                              "description": "Tração 4x4"                                              
                                            },
                                            {
                                              "description": "4 portas"                                              
                                            },
                                            {
                                              "description": "Diesel"                                              
                                            },
                                            {
                                              "description": "Air bag"                                              
                                            },
                                            {
                                              "description": "ABS"                                              
                                            }
                                          ],
                                        "passengersQtd": 5                                        
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "400": {
                        "description" : "Bad Request"
                    },
                    "201" : {
                        "description" : "Veículo registrado com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/car"                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/car/" : {
            "get" : {
                "description" : "Busca todos os veículos cadastrados",
                "summary" : "Busca todos os veículos cadastrados",
                "tags" : ["Car"],
                "responses" : {
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/car"                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/car/{listCarId}" : {
            "get" : {
                "description" : "Busca um veículo cadastrado pelo ID",
                "summary" : "Busca um veículo cadastrado pelo ID",
                "tags" : ["Car"],
                "parameters" :  [
                    {
                        "name" : "listCarId",
                        "in" : "path",
                        "description" : "Id de veículo cadastrado para busca",
                        "required" : true
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "Veículo encontrado com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/car"                                    
                                }
                            }
                        }
                    }
                }
            }            
        },
        "/car/{putCar}" : {
            "put" : {                
                "description" : "Atualiza os dados de um veículo cadastrado pelo ID",
                "summary" : "Atualiza os dados de um veículo cadastrado pelo ID",
                "tags" : ["Car"],
                "security" : [{ "bearerAuth" : [] }],
                "parameters" :  [
                    {
                        "name" : "putCar",
                        "in" : "path",
                        "description" : "Id de veículo cadastrado para busca",
                        "required" : true
                    }
                ],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/car"                                 
                            },
                            "examples" : {
                                "car" : {
                                    "value" : {
                                        "model" : "S10 2.8",
                                        "type" : "Sedan",
                                        "brand" : "GM",
                                        "color" : "branco",
                                        "year" : "2021",                                        
                                        "accessories": [
                                            {
                                              "description": "Ar-condicionado"                                              
                                            },
                                            {
                                              "description": "Dir. Hidráulica"                                              
                                            },
                                            {
                                              "description": "Cabine Dupla"                                              
                                            },
                                            {
                                              "description": "Tração 4x4"                                              
                                            },
                                            {
                                              "description": "4 portas"                                              
                                            },
                                            {
                                              "description": "Diesel"                                              
                                            },
                                            {
                                              "description": "Air bag"                                              
                                            },
                                            {
                                              "description": "ABS"                                              
                                            }
                                          ],
                                        "passengersQtd": 5                                        
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "200" : {
                        "description" : "Veículo atualizado com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/car"                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/car/{deleteCar}" : {
            "delete" : {
                "description" : "Exclui os dados de um veículo cadastrado pelo ID",
                "summary" : "Exclui os dados de um veículo cadastrado pelo ID",
                "tags" : ["Car"],
                "parameters" :  [
                    {
                        "name" : "deleteCar",
                        "in" : "path",
                        "description" : "Id de veículo cadastrado para busca e exclusão dos dados",
                        "required" : true
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "Dados do veículo excluído com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/car"                                    
                                }
                            }
                        }
                    }
                }
            }            
        },
        "/rental" : {
            "post" : {
                "summary" : "Cadastro de locadora de veículos",
                "description" : "Essa rota será responsável por cadastrar uma nova locadora de veículos usuário",
                "tags" : ["Rental"],
                "security" : [{"bearerAuth" : []}],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/rental"                                 
                            },
                            "examples" : {
                                "person" : {
                                    "value" : {
                                        "name" : "Localiza Rent a Car",
                                        "cnpj": "16.670.085/0001-55",
                                        "activities": "Aluguel de Carros E Gestão de Frotas",
                                        "address": [{
                                            "zipCode": "96200-200",
                                            "street": "Rua General Canabarro",
                                            "complement": "Muro A",
                                            "district": "Centro",
                                            "number":"1234",
                                            "city": "Rio Grande",
                                            "state": "RS"
                                            }]      
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "400": {
                        "description" : "Bad Request"
                    },
                    "201" : {
                        "description" : "Locadora cadastrada com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/rental"                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rental/" : {
            "get" : {
                "description" : "Busca todos as locadoras de veículos cadastradas",
                "summary" : "Busca todos as locadoras de veículos cadastradas",
                "tags" : ["Rental"],
                "responses" : {
                    "200" : {
                        "description" : "OK",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/rental"                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rental/{listId}" : {
            "get" : {
                "description" : "Busca uma locadora de veículo cadastrada pelo ID",
                "summary" : "Busca uma locadora de veículo cadastrada pelo ID",
                "tags" : ["Rental"],
                "parameters" :  [
                    {
                        "name" : "listId",
                        "in" : "path",
                        "description" : "Id de locadora de veículo cadastrada para busca",
                        "required" : true
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "locadora de veículo encontrada com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/rental"                                    
                                }
                            }
                        }
                    }
                }
            }            
        },
        "/rental/{update}" : {
            "put" : {                
                "description" : "Atualiza os dados de uma locadora de veículos cadastrada pelo ID",
                "summary" : "Atualiza os dados de uma locadora de veículos cadastrada pelo ID",
                "tags" : ["Rental"],
                "security" : [{ "bearerAuth" : [] }],
                "parameters" :  [
                    {
                        "name" : "update",
                        "in" : "path",
                        "description" : "Id de locadora cadastrada para busca",
                        "required" : true
                    }
                ],
                "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "$ref" : "#/components/schemas/rental"                                 
                            },
                            "examples" : {
                                "rental" : {
                                    "value" : {
                                        "name" : "Localiza Rent a Car",
                                        "cnpj": "16.670.085/0001-55",
                                        "activities": "Aluguel de Carros E Gestão de Frotas",
                                        "address": [{
                                            "zipCode": "96200-200",
                                            "street": "Rua General Canabarro",
                                            "complement": "Muro A",
                                            "district": "Centro",
                                            "number":"1234",
                                            "city": "Rio Grande",
                                            "state": "RS"
                                            }]      
                                    }
                                }
                            }
                        }
                    }
                },
                "responses" : {
                    "200" : {
                        "description" : "Dados de locadora atualizados com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/rental"                                    
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rental/{delete}" : {
            "delete" : {
                "description" : "Exclui os dados de uma locadora veículos cadastrada pelo ID",
                "summary" : "Exclui os dados de uma locadora veículos cadastrada pelo ID",
                "tags" : ["Rental"],
                "parameters" :  [
                    {
                        "name" : "delete",
                        "in" : "path",
                        "description" : "Id de locadora de veículos cadastrado para busca e exclusão dos dados",
                        "required" : true
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "Dados da locadora de veículos excluídos com sucesso!",
                        "content" : {
                            "application/json" : {
                                "schema" : {
                                    "type" : "object",                                    
                                    "$ref" : "#/components/schemas/rental"                                    
                                }
                            }
                        }
                    }
                }
            }            
        }        
    },
    "components" : {
        "schemas" : {
            "car" : {
                "type" : "object",
                "properties" : {
                    "model" : {
                        "type" : "String",
                        "requered" : true
                    },
                    "type" : {
                        "type" : "String",
                        "requered" : true
                    },
                    "brand" : {
                        "type" : "String",
                        "requered" : true
                    },
                    "color" : {
                        "type" : "String",
                        "requered" : true
                    },
                    "year" : {
                        "type" : "Date",
                        "requered" : true
                    },                    
                    "accessories" :[{
                        "description" : {
                            "type" : "String",
                            "required" : true			
                        }
                        
                    }],
                    "passengersQtd" : {
                        "type" : "Number",
                        "required" : true
                    }
                }
                
            }
        },
        "securitySchemas" : {
            "bearerAuth" : {
                "type" : "http",
                "scheme" : "bearer",
                "beareFormat" : "JWT"
            }
        }        
    }
}